import RuledV5

#print axioms RuledV5.actual_projection_jacobian
#print axioms RuledV5.angular_boundary_left_inverse
#print axioms RuledV5.angular_field_boundary_diverges
#print axioms RuledV5.angular_field_boundary_residue
#print axioms RuledV5.angular_qChart_range
#print axioms RuledV5.angular_transition_contDiffAt
#print axioms RuledV5.angular_transition_hasFDerivAt
#print axioms RuledV5.angular_transition_isSmoothChartAt
#print axioms RuledV5.arctan_remainder_bound
#print axioms RuledV5.arctan_remainder_nonneg
#print axioms RuledV5.areaVector_eq
#print axioms RuledV5.areaVector_zero_iff_observation_zero
#print axioms RuledV5.asymptote_cos_bounds
#print axioms RuledV5.asymptote_cos_cubic
#print axioms RuledV5.asymptote_not_critical
#print axioms RuledV5.asymptote_unique_cubic_root
#print axioms RuledV5.boundaryAngle_contDiffAt
#print axioms RuledV5.boundaryAngle_cos_sin
#print axioms RuledV5.boundaryAngle_qChart
#print axioms RuledV5.boundaryAngle_surface_inverse
#print axioms RuledV5.boundaryC_at_zero
#print axioms RuledV5.boundaryC_bounds
#print axioms RuledV5.boundaryC_circle_identity
#print axioms RuledV5.boundaryC_contDiffAt
#print axioms RuledV5.boundaryC_hasDerivAt
#print axioms RuledV5.boundaryC_hasDerivAt_zero
#print axioms RuledV5.boundaryC_qChart
#print axioms RuledV5.boundaryS_at_zero
#print axioms RuledV5.boundaryS_hasDerivAt
#print axioms RuledV5.boundaryS_hasDerivAt_zero
#print axioms RuledV5.boundary_actual_area_transform
#print axioms RuledV5.boundary_actual_observation_transform
#print axioms RuledV5.boundary_actual_tangent_basis
#print axioms RuledV5.boundary_angle_hasDerivAt
#print axioms RuledV5.boundary_angle_rate_physical
#print axioms RuledV5.boundary_areaVector
#print axioms RuledV5.boundary_contDiffAt
#print axioms RuledV5.boundary_coordinate_homeomorphism
#print axioms RuledV5.boundary_corner_kernel
#print axioms RuledV5.boundary_derivative_basis
#print axioms RuledV5.boundary_hasFDerivAt
#print axioms RuledV5.boundary_matches_interior
#print axioms RuledV5.boundary_observation_at_edge
#print axioms RuledV5.boundary_observation_limit
#print axioms RuledV5.boundary_pairing_constraint
#print axioms RuledV5.boundary_pairing_regular_at_zero
#print axioms RuledV5.boundary_regular_iff
#print axioms RuledV5.boundary_second_u
#print axioms RuledV5.boundary_surface_contDiffAt
#print axioms RuledV5.boundary_transition_contDiffAt
#print axioms RuledV5.boundary_transition_hasFDerivAt
#print axioms RuledV5.chart_phase_actual
#print axioms RuledV5.chart_phase_doubled_harmonic_dominates
#print axioms RuledV5.chart_phase_error
#print axioms RuledV5.chart_phase_odd_cosine_coeff_zero
#print axioms RuledV5.chart_phase_pi_periodic
#print axioms RuledV5.chart_phase_sine_coeff_zero
#print axioms RuledV5.circle_value_endpoints
#print axioms RuledV5.circle_value_norm
#print axioms RuledV5.completed_singular_parameters
#print axioms RuledV5.complex_circle_parameter
#print axioms RuledV5.complex_observation_components
#print axioms RuledV5.coreP_root_iff
#print axioms RuledV5.corner_paths_eventually_regular
#print axioms RuledV5.corner_scaled_area_limit
#print axioms RuledV5.corner_scaled_tangent_actual
#print axioms RuledV5.corner_scaled_tangent_limit
#print axioms RuledV5.corner_tangent_u_limit
#print axioms RuledV5.cosine_coefficient_error
#print axioms RuledV5.cosine_coefficient_uniform_bound
#print axioms RuledV5.cosine_leading_coefficient
#print axioms RuledV5.cross_gram_identity
#print axioms RuledV5.curvature_zero_iff_parameter
#print axioms RuledV5.differential_injective_iff_cross
#print axioms RuledV5.dual_vector_apply
#print axioms RuledV5.ellipse_loop_endpoints
#print axioms RuledV5.ellipse_loop_winding
#print axioms RuledV5.ellipse_ne_zero
#print axioms RuledV5.entire_skeleton_critical_intersection
#print axioms RuledV5.euclideanSq_pos_iff
#print axioms RuledV5.exponential_loop_closed
#print axioms RuledV5.exponential_loop_index
#print axioms RuledV5.exponential_loop_winding
#print axioms RuledV5.first_form_E
#print axioms RuledV5.first_form_F
#print axioms RuledV5.first_form_G
#print axioms RuledV5.gaussian_curvature_boundary_edge
#print axioms RuledV5.gaussian_curvature_boundary_overlap
#print axioms RuledV5.gaussian_curvature_congr
#print axioms RuledV5.gaussian_curvature_negative_iff
#print axioms RuledV5.gaussian_curvature_nonpos
#print axioms RuledV5.gaussian_curvature_raw
#print axioms RuledV5.gaussian_curvature_ruled
#print axioms RuledV5.gaussian_curvature_separated
#print axioms RuledV5.global_angle_contDiffAt
#print axioms RuledV5.global_angle_continuous
#print axioms RuledV5.global_angle_hasDerivAt
#print axioms RuledV5.global_angle_odd
#print axioms RuledV5.global_angle_range
#print axioms RuledV5.global_angle_smooth_formula
#print axioms RuledV5.global_angle_strictMonoOn
#print axioms RuledV5.global_angle_trig
#print axioms RuledV5.global_angular_overlap_isSmoothChartAt
#print axioms RuledV5.global_base_map_bijective
#print axioms RuledV5.global_boundary_overlap_isSmoothChartAt
#print axioms RuledV5.global_boundary_surface_actual
#print axioms RuledV5.global_c_bounds
#print axioms RuledV5.global_c_strictAntiOn
#print axioms RuledV5.global_circle_identities
#print axioms RuledV5.global_domain_homeomorphism
#print axioms RuledV5.global_domain_isManifold
#print axioms RuledV5.global_q_actual
#print axioms RuledV5.global_q_contDiffAt
#print axioms RuledV5.global_q_hasDerivAt_edge
#print axioms RuledV5.global_radicands_positive
#print axioms RuledV5.global_surface_actual
#print axioms RuledV5.global_surface_contDiffAt
#print axioms RuledV5.global_surface_contMDiff
#print axioms RuledV5.integral_cos_integer
#print axioms RuledV5.interior_regular_iff
#print axioms RuledV5.interior_singular_parameters
#print axioms RuledV5.intersection_cos_bounds
#print axioms RuledV5.intersection_cos_physical
#print axioms RuledV5.intersection_cos_unique
#print axioms RuledV5.jacobian_odd
#print axioms RuledV5.lateral_actual_local_inverses
#print axioms RuledV5.lateral_dipole_indices
#print axioms RuledV5.lateral_jacobian
#print axioms RuledV5.lateral_jacobians_nonzero
#print axioms RuledV5.lateral_observation_indices
#print axioms RuledV5.lateral_parameters_bounds
#print axioms RuledV5.linear_circle_winding
#print axioms RuledV5.local_fold_common_neighborhood
#print axioms RuledV5.local_fold_fiber_criterion
#print axioms RuledV5.local_observation_index_eq_of_has
#print axioms RuledV5.local_observation_index_unique
#print axioms RuledV5.loop_winding_based
#print axioms RuledV5.loop_winding_free_homotopy
#print axioms RuledV5.loop_winding_integral
#print axioms RuledV5.loop_winding_normalized
#print axioms RuledV5.negative_curvature_witness
#print axioms RuledV5.negative_lateral_jacobian_positive
#print axioms RuledV5.no_continuous_corner_normal
#print axioms RuledV5.no_continuous_corner_normal_local
#print axioms RuledV5.no_corner_flattening_chart
#print axioms RuledV5.no_regular_corner_level_set
#print axioms RuledV5.nondegenerate_zero_circle_winding
#print axioms RuledV5.nondegenerate_zero_small_homotopy
#print axioms RuledV5.normalized_loop_start
#print axioms RuledV5.numerator_on_N_zero
#print axioms RuledV5.observationM_negative_iff
#print axioms RuledV5.observationM_positive_iff
#print axioms RuledV5.observationM_skeleton_factor
#print axioms RuledV5.observation_even
#print axioms RuledV5.observation_index_of_nondegenerate_zero
#print axioms RuledV5.observation_local_inverse
#print axioms RuledV5.observation_zero_circle_winding
#print axioms RuledV5.observation_zero_iff
#print axioms RuledV5.off_skeleton_phase_not_axis
#print axioms RuledV5.paired_boundary_images_at_u_one
#print axioms RuledV5.paired_label_image_at_u_one
#print axioms RuledV5.pairing_constraint_hasFDerivAt
#print axioms RuledV5.pairing_constraint_regular
#print axioms RuledV5.patch_second_comp
#print axioms RuledV5.patch_second_iterated
#print axioms RuledV5.phaseD_pos
#print axioms RuledV5.phase_lock_iff
#print axioms RuledV5.phase_locked_retracing
#print axioms RuledV5.phase_response_error_bound
#print axioms RuledV5.phase_response_half_period
#print axioms RuledV5.phase_response_positive_period
#print axioms RuledV5.physical_boundary_strict_bounds
#print axioms RuledV5.physical_cos_labels
#print axioms RuledV5.polar_has_no_interior_index
#print axioms RuledV5.polar_jacobian_zero
#print axioms RuledV5.polar_observation_index_none
#print axioms RuledV5.polar_observation_zero
#print axioms RuledV5.positive_lateral_jacobian_negative
#print axioms RuledV5.projection_hasFDerivAt
#print axioms RuledV5.rational_intersection_surface_regular
#print axioms RuledV5.repeated_nonzero_signal_iff_phase_lock
#print axioms RuledV5.ruled_normal_orthogonal
#print axioms RuledV5.ruled_not_developable
#print axioms RuledV5.ruled_second_eq_iterated
#print axioms RuledV5.ruled_second_symmetric
#print axioms RuledV5.ruled_second_u
#print axioms RuledV5.ruled_unit_normal
#print axioms RuledV5.ruling_hasFDerivAt
#print axioms RuledV5.ruling_metric_endpoint_values
#print axioms RuledV5.ruling_metric_range
#print axioms RuledV5.ruling_mixed_derivative
#print axioms RuledV5.scalar_triple_product
#print axioms RuledV5.separated_first_jet
#print axioms RuledV5.separated_second_basis
#print axioms RuledV5.separated_second_jet
#print axioms RuledV5.separated_tangent_basis
#print axioms RuledV5.signed_angular_boundary_left_inverse
#print axioms RuledV5.singularParameters_card
#print axioms RuledV5.singularParameters_physical
#print axioms RuledV5.skeleton_equation_iff
#print axioms RuledV5.skeleton_height_physical
#print axioms RuledV5.skeleton_nonzero_phase_classification
#print axioms RuledV5.skeleton_phase_pi_iff
#print axioms RuledV5.skeleton_phase_zero_iff
#print axioms RuledV5.smooth_chart_fderiv_bijective
#print axioms RuledV5.squared_cosine_response
#print axioms RuledV5.surface_contDiffAt
#print axioms RuledV5.surface_fderiv_basis
#print axioms RuledV5.surface_hasFDerivAt
#print axioms RuledV5.transition_derivative_nonzero
#print axioms RuledV5.transition_left_inverse
#print axioms RuledV5.transition_right_inverse
#print axioms RuledV5.transverse_crossing_derivative
#print axioms RuledV5.transverse_crossing_observation_injective
#print axioms RuledV5.uniform_remainder_sine_coefficient_zero
#print axioms RuledV5.uniform_rotation_phase_lock
#print axioms RuledV5.unlocked_rotation_counterexample
#print axioms RuledV5.unlocked_rotation_counterexample_nonreal
#print axioms RuledV5.whitney_fiber_iff
#print axioms RuledV5.winding_lift_actual
#print axioms RuledV5.winding_value_homotopy_invariant
#print axioms RuledV5.winding_value_initial_independent
#print axioms RuledV5.winding_value_integral
#print axioms RuledV5.zero_signal
