"""Assemble the Version 1 release files of the two Bicomplex successor papers.

Writes releases/candidates/bicomplex-successor-v1/ : the two article PDFs, one
source zip per article (TeX plus the figures it includes), the software source
zip and SHA256SUMS.txt. The zips are deterministic (fixed timestamps, sorted
members). The private v7 draft is never included.
"""
from pathlib import Path
import hashlib
import json
import re
import zipfile

ROOT = Path(__file__).resolve().parents[4]
B = ROOT / "papers/legacy-geometry/bicomplex-signal-manifolds"
OUT = ROOT / "releases/candidates/bicomplex-successor-v1"
STAMP = (2026, 10, 2, 0, 0, 0)
P1 = "Realization_Limits_Bicomplex_Signal_Surface"
P2 = "Pseudo_Laplacians_Whitney_Cross_Caps"
DOI = {"paper1": "10.5281/zenodo.23103026", "paper2": "10.5281/zenodo.23103056",
       "software": "10.5281/zenodo.23103299"}
SOFT = "bicomplex-successor-v1.0-software"

VERIFIERS = ["build_successor_figures.py", "build_successor_paper1_pdf.py",
             "build_successor_paper2_pdf.py", "verify_successor_paper1.py",
             "verify_successor_paper2.py", "verify_revision.py", "verify_continuation.py",
             "verify_continuation_0_04.py", "verify_local_algebra.py",
             "verify_crosscap_models.py", "verify_spectral_algebra.py"]

LICENSE = """# License policy

Copyright 2026 Akari Hayami (Jian-Yu Huang).

This package uses a mixed license determined by file type.

## Software

Lean (`.lean`) and Python (`.py`) source code, with executable build and
verification configuration (`lakefile.toml`, `lake-manifest.json`,
`lean-toolchain`, `requirements.txt`), is licensed under the Apache License,
Version 2.0 (`Apache-2.0`): <https://www.apache.org/licenses/LICENSE-2.0>.
Unless required by applicable law or agreed to in writing, software distributed
under this license is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied.

## Scholarly and documentation material

The two article TeX sources, original figures, Markdown documentation, claim
maps and citation metadata are licensed under the Creative Commons Attribution
4.0 International License (`CC-BY-4.0`):
<https://creativecommons.org/licenses/by/4.0/legalcode>.

## Third-party and historical material

`papers/legacy-geometry/source-registry/` holds two earlier public files of the
author (v11, v12), included only so that their SHA-256 hashes can be replayed,
and `source_ancestor/` holds the author's earlier TeX source; both are covered
by CC-BY-4.0 as the author's own material. Third-party dependencies (Lean,
Mathlib, Python packages) keep their own licenses.

When a file contains a more specific license notice, that notice controls.
"""

README = f"""# Verification Companion for Realization Limits and Pseudo-Laplacians at Whitney Cross-Caps (version 1.0)

Software and source companion to two preprints by Akari Hayami (Jian-Yu Huang):

- *Realization Limits of the Bicomplex Signal Surface: Analytic Rigidity, Smooth
  Flexibility and Observation Monodromy*, doi:{DOI['paper1']};
- *Pseudo-Laplacians at Whitney Cross-Caps: Point Interactions on Surfaces Mapped
  into Three-Space*, doi:{DOI['paper2']}.

This package: doi:{DOI['software']}. It corrects and succeeds the preprint
*Geometric Realization of Bicomplex Signal Manifolds* (ResearchGate 408878000,
doi:10.13140/RG.2.2.17048.15361); the earlier record is kept unchanged.

## Contents

| Path | What it is |
| --- | --- |
| `papers/legacy-geometry/bicomplex-signal-manifolds/successor/` | TeX of both articles, the ten figures and `figures/FIGURES_MANIFEST.json` (SHA-256 of each figure) |
| `.../verification/` | exact and finite verifiers, the figure generator and the two PDF builders |
| `.../claims/` | `CLAIM_MAP.json`/`.md` (all 66 named statements of v12 with their audit status), V11 comparison, index of the private v7 draft |
| `.../source_ancestor/` | the earlier TeX source, hash-checked by the verifiers |
| `papers/legacy-geometry/source-registry/` | the public v12 and v11 PDFs of the earlier preprint, hash-checked by the verifiers |
| `companions/lean/bicomplex-signal-manifolds/` | Lean 4 / Mathlib project: 33 named theorems with `COVERAGE.md` |

## Replay

```sh
python3 -m venv local/venv
local/venv/bin/python -m pip install -r requirements.txt
local/venv/bin/python -B verify.py
```

`verify.py` runs both successor verifiers, which in turn replay the earlier exact
verifiers. Never use Python optimization (`-O`): the verifiers rely on assertions.
PDF rebuilds are separate (`verification/build_successor_paper1_pdf.py` and
`..._paper2_pdf.py`; they need `pdflatex`), and the figures are regenerated by
`verification/build_successor_figures.py` (they must reproduce the hashes in the
manifest only on the pinned library versions).

## Scope

- **What the scripts check.** Exact algebra, explicit formulas, finite numerical
  replays, the figure hashes, the 66-block correction table and the cross-references.
  They do not certify the analytic proofs; those are written in the articles with
  stated external theorems.
- **Lean.** The Lean project contains 33 own theorems (partial coverage of selected
  statements, listed in `COVERAGE.md`). It is not a formalization of either paper.
  Building it needs Lean 4.33.1, Mathlib and the sibling projects `ruled-surface-v5`
  and `stokes-caustic-v5` of the repository
  <https://github.com/Akari-H-111/hayami-mathematical-research>, which `lakefile.toml`
  references by relative path; the Lean sources are included here for reading and for
  use inside a checkout of that repository.
- **The v7 draft.** A private 26-page draft whose statements are discussed in the
  articles is not distributed. Its SHA-256 is recorded in `claims/V7_DRAFT_INDEX.md`;
  `verify_continuation_0_04.py` checks the hash when the file is present and otherwise
  reports that the draft is not distributed.

## License

Code and build configuration: Apache-2.0. Original TeX, figures and documentation:
CC-BY-4.0. See `LICENSE.md`.
"""

REQUIREMENTS = """numpy
matplotlib
sympy
mpmath
"""

VERIFY = '''"""Run the two successor verifiers (which replay the earlier exact verifiers)."""
from pathlib import Path
import subprocess
import sys

V = Path(__file__).resolve().parent / "papers/legacy-geometry/bicomplex-signal-manifolds/verification"


def main():
    assert not sys.flags.optimize
    for name in ("verify_successor_paper1.py", "verify_successor_paper2.py"):
        result = subprocess.run([sys.executable, "-B", str(V / name)], text=True,
                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        print(result.stdout, end="")
        if result.returncode:
            raise SystemExit(f"FAIL {name}")
    print("PASS all successor verifiers")


if __name__ == "__main__":
    main()
'''


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write_zip(path, members):
    """members: list of (archive name, bytes)."""
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for name, data in sorted(members):
            info = zipfile.ZipInfo(name, STAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, data)


def figures_used(tex):
    return sorted(set(re.findall(r"\\includegraphics(?:\[[^]]*\])?\{([^}]+)\}", tex.read_text())))


def article_zip(stem):
    tex = B / "successor" / f"{stem}.tex"
    members = [(f"{stem}/{tex.name}", tex.read_bytes())]
    for name in figures_used(tex):
        members.append((f"{stem}/figures/{name}", (B / "successor/figures" / name).read_bytes()))
    write_zip(OUT / f"{stem}_source.zip", members)


def software_zip():
    files = {}

    def add(rel, src=None, data=None):
        files[f"{SOFT}/{rel}"] = data if data is not None else Path(src).read_bytes()

    base = "papers/legacy-geometry/bicomplex-signal-manifolds"
    for name in VERIFIERS:
        add(f"{base}/verification/{name}", B / "verification" / name)
    for stem in (P1, P2):
        add(f"{base}/successor/{stem}.tex", B / "successor" / f"{stem}.tex")
    for fig in sorted((B / "successor/figures").iterdir()):
        add(f"{base}/successor/figures/{fig.name}", fig)
    for name in ("CLAIM_MAP.json", "CLAIM_MAP.md", "V11_COMPARISON.md", "V7_DRAFT_INDEX.md"):
        add(f"{base}/claims/{name}", B / "claims" / name)
    add(f"{base}/source_ancestor/signal_manifolds_v2.tex", B / "source_ancestor/signal_manifolds_v2.tex")
    reg = ROOT / "papers/legacy-geometry/source-registry"
    add("papers/legacy-geometry/source-registry/final_pdfs/Geometric_Realization_of_Bicomplex_Signal_Manifolds_v12.pdf",
        reg / "final_pdfs/Geometric_Realization_of_Bicomplex_Signal_Manifolds_v12.pdf")
    add("papers/legacy-geometry/source-registry/historical_drafts/Geometric_Realization_of_Bicomplex_Signal_Manifolds_v11.pdf",
        reg / "historical_drafts/Geometric_Realization_of_Bicomplex_Signal_Manifolds_v11.pdf")
    lean = ROOT / "companions/lean/bicomplex-signal-manifolds"
    for path in sorted(lean.rglob("*")):
        if path.is_file() and ".lake" not in path.parts:
            add(f"companions/lean/bicomplex-signal-manifolds/{path.relative_to(lean).as_posix()}", path)
    add("LICENSE.md", data=LICENSE.encode())
    add("README.md", data=README.encode())
    add("requirements.txt", data=REQUIREMENTS.encode())
    add("verify.py", data=VERIFY.encode())
    meta = {
        "distribution": "software-and-source",
        "software_version": "1.0",
        "date": "2026-10-02",
        "author": "Akari Hayami (Jian-Yu Huang)",
        "software_doi": DOI["software"],
        "paper1_doi": DOI["paper1"],
        "paper2_doi": DOI["paper2"],
        "public_named_theorems": 33,
        "lean_coverage": "partial: selected statements listed in companions/lean/bicomplex-signal-manifolds/COVERAGE.md; not a formalization of either paper",
        "private_v7_draft_distributed": False,
        "supersedes_record": "ResearchGate 408878000, doi:10.13140/RG.2.2.17048.15361 (kept unchanged)",
        "license": "Apache-2.0 code/build; CC-BY-4.0 original scholarly material",
    }
    add("METADATA.json", data=(json.dumps(meta, indent=2) + "\n").encode())
    assert not any("_v7.pdf" in name for name in files)
    sums = "".join(f"{hashlib.sha256(d).hexdigest()}  {n[len(SOFT) + 1:]}\n" for n, d in sorted(files.items()))
    files[f"{SOFT}/SHA256SUMS.txt"] = sums.encode()
    write_zip(OUT / f"{SOFT}-source.zip", list(files.items()))
    (OUT / f"{SOFT}-SHA256SUMS.txt").write_bytes(sums.encode())


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for stem in (P1, P2):
        (OUT / f"{stem}.pdf").write_bytes((B / "successor" / f"{stem}.pdf").read_bytes())
        article_zip(stem)
    software_zip()
    lines = "".join(f"{sha(p)}  {p.name}\n" for p in sorted(OUT.iterdir()) if p.name != "SHA256SUMS.txt")
    (OUT / "SHA256SUMS.txt").write_text(lines)
    print(lines, end="")


if __name__ == "__main__":
    main()
