"""Reproduce the illustrated edition from the unchanged v0.08 manuscript."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
text = (ROOT / 'provenance/paper_III_spectral_floor_v0_08.tex').read_text()
text = text.replace('Paper III, manuscript closeout v0.08', 'Paper III, illustrated edition v0.09')
text = text.replace('Akari H.', 'Akari Hayami (Jian-Yu Huang)')
preamble = r'''
% BEGIN ILLUSTRATION PREAMBLE
\usepackage{graphicx}
\usepackage{placeins}
\raggedbottom
\setlength{\textfloatsep}{12pt plus 2pt minus 2pt}
\setlength{\intextsep}{12pt plus 2pt minus 2pt}
\renewcommand{\topfraction}{0.9}
\renewcommand{\bottomfraction}{0.8}
\renewcommand{\textfraction}{0.08}
\renewcommand{\floatpagefraction}{0.7}
% END ILLUSTRATION PREAMBLE
'''
text = text.replace(r'\begin{document}', preamble + r'\begin{document}', 1)
figures = [
    (r'\section{Normalized tilts and spectral floors}', 'fig01_master_pipeline',
     r'Figure~\ref{fig:master-pipeline} displays the finite assembly with its supplied data and landing-descent hypothesis.',
     r'The marked spectral-floor pipeline. The identification $K_\infty\simeq W/\ker\Lambda$ and its induced dynamics require $T\ker\Lambda\subseteq\ker\Lambda$. The output concerns the full original tilt orbit on $R_\Lambda=\im\Lambda$. The marking and state, source and landing maps are supplied, as in Theorem~\ref{thm:assembly}; they are not reconstructed from a bare complex.', 'master-pipeline'),
    (r'\begin{remark}[Cubic specialization]', 'fig02_invariant_tilt_floor',
     r'The exact variation space and two-witness argument in Theorem~\ref{thm:floor} are summarized in Figure~\ref{fig:invariant-tilt-floor}.',
     r'The invariant normalized-tilt floor. With $K$ invariant, a chosen complement exposes arbitrary off-diagonal and quotient blocks. For a nonzero complement, two distinct scalar quotient blocks witness both monic gcds, including the case in which a scalar is a root of the forced polynomial. The zero-complement and zero-space cases use the stated conventions.', 'invariant-tilt-floor'),
    (r'\section{Forced-sector extraction from finite landing data}', 'fig03_stable_core_floor',
     r'Figure~\ref{fig:stable-core-floor} follows the proof of Theorem~\ref{thm:stable-floor} without enlarging the allowed perturbation family.',
     r'The stable-core floor without invariant normalization. Spectral avoidance over the infinite base field supplies two quotient blocks in the original orbit. Their coprime spectra also split the minimal-polynomial extension. The preserved action is on $U$, but the perturbations still vanish on the original kernel $K$.', 'stable-core-floor'),
    (r'\begin{corollary}[Cyclic polynomial module]', 'fig04_landing_future_output',
     r'Figure~\ref{fig:landing-future} distinguishes static extraction, global descent, local descent and the future-output quotient of Proposition~\ref{prop:local-descent}.',
     r'Landing and retained future outputs. Static extraction is a vector-space statement. Global descent supplies the shorter stable quotient; local descent supplies dynamics only on $\Lambda W$. When local descent fails, $W/J_{\rm fut}$ is the smallest quotient preserving all future landing outputs. It can be larger than $\Lambda W$ and does not supply an operator on the original static landing space.', 'landing-future'),
    (r'\section{Syzygies and the constraint propagator}', 'fig05_generated_source',
     r'The closure construction, minimality and generated-coverage criterion are collected in Figure~\ref{fig:generated-source}.',
     r'Generating the normalized source. Intertwining maps preserve the generated source. For an invertible ambient comparison, equality is equivalent to coverage of the target seeds by the generated image; surjectivity onto the target seed image itself is not necessary. The last panel specializes to the relation module on $H_0$ and its supplied embedding into $F$.', 'generated-source'),
    (r'\section{Finite closure and assembly}', 'fig06_syzygy_algebra',
     r'Figure~\ref{fig:syzygy-algebra} compares the syzygy action and the algebra generated by the corresponding descended marks.',
     r'From syzygies to the effective equation algebra. The two represented algebras are identified after transporting the same action through the presentation isomorphism. Conjugacy under a homotopy-compatible comparison requires an isomorphism on $H_0$, as in Proposition~\ref{prop:algebra-comparison}. No ambient extension outside the relation image is needed.', 'syzygy-algebra'),
    (r'The output is transported by isomorphisms of the full marked data:', 'fig07_stable_assembly',
     r'Figure~\ref{fig:stable-assembly} separates operator closure, source closure and the stable quotient in Theorem~\ref{thm:assembly}.',
     r'Finite closure and stable assembly. The first two iterations terminate by finite dimension. Under landing descent, $\widetilde T$ is the operator induced on $W/\ker\Lambda$, and its two polynomials are the forced divisors for the unchanged full orbit. Nilpotence of the filtration-shift ideal additionally requires the whole effective algebra to preserve the filtration.', 'stable-assembly'),
    (r'For an end-to-end marked realization, take', 'fig08_exact_floor',
     r'Figure~\ref{fig:exact-floor} displays the noninvariant kernel and both rational witnesses in this example.',
     r'An exact noninvariant-normalization floor. The matrices for $\tau_0$ and $\tau_1$ are cyclic, so the displayed characteristic and minimal polynomials coincide for each witness. Their gcd is $S-2$, precisely the polynomial of the invariant core $\Q e_2$. All variations remain confined to the third column.', 'exact-floor'),
    (r'\section{Scope boundary and conclusion}', 'fig09_marked_realization',
     r'The supplied maps and every stage of this realization are shown together in Figure~\ref{fig:marked-realization}.',
     r'One complete marked realization of stable assembly. The quotient $F/N$ is identified with $\Q$ by $q(y_1,y_2)=y_2$. Landing descent holds because $\Lambda=I$, whereas normalized closure fails. The stable-core theorem still gives both floors equal to $S-2$. This finite model does not assert canonical origin of the inputs in every inverse-Leibniz presentation.', 'marked-realization'),
    (r'Within the specified marked category, the sequence', 'fig10_marked_scope',
     r'Figure~\ref{fig:marked-scope} exhibits the two markings on the same filtered complex used in the preceding scope argument.',
     r'Marked reconstruction and its scope boundary. The shift-only and shift-plus-weight markings generate algebras of dimensions $4$ and $10$ on the same filtered object. Thus the unmarked object does not determine which marking was intended. This does not exclude scalar maps such as the identity or a more restrictive geometric construction supplying additional operators.', 'marked-scope'),
]
for number, (anchor, stem, callout, caption, label) in enumerate(figures, 1):
    assert text.count(anchor) == 1, anchor
    block = ('\n% BEGIN ILLUSTRATION ' + str(number) + '\n' + callout + '\n'
             + '\\begin{figure}[htbp]\n\\centering\n'
             + '\\includegraphics[width=\\linewidth]{figures/' + stem + '.pdf}\n'
             + '\\caption{' + caption + '}\n\\label{fig:' + label + '}\n'
             + '\\end{figure}\n\\FloatBarrier\n% END ILLUSTRATION ' + str(number) + '\n\n')
    text = text.replace(anchor, block + anchor, 1)
note = r'''
% BEGIN ILLUSTRATION EVIDENCE NOTE
\paragraph{Illustrated-edition supplement.}
The portable source package contains ten native vector figure masters,
the unchanged v0.57--v0.61 finite verifiers in
\path{evidence/verification/part_III/}, and the bundled v0.02/v0.03
recovery checks with their required inputs. Run \path{verify_evidence.py}
for the finite replay and \path{verify_integrated.py} for manuscript and
PDF checks. The v0.08 three-paper archive remains the broader companion;
its cited editions and the mathematical body are retained. The illustrations
summarize the proofs and finite models and do not replace them.
% END ILLUSTRATION EVIDENCE NOTE

'''
anchor = r'\begin{thebibliography}{99}'
assert text.count(anchor) == 1
text = text.replace(anchor, note + anchor, 1)
(ROOT / 'paper_III_spectral_floor_v0_09.tex').write_text(text)
print('Integrated ten figures; original mathematics retained and author name updated.')
