import sympy as sp

z=sp.symbols("z")
E=z+2
q=z**5-4*z**4+12*z**3-32*z**2+80*z-192
mA=sp.expand(E*q)
p3=sp.expand(E*mA)
p4=sp.expand(E*p3)
p5=sp.expand(mA*p4)

assert sp.expand(p4-E**2*mA)==0
assert sp.expand(p5-mA*p4)==0
assert sp.rem(p3*E**2,p4,z)==0
assert sp.rem(p4**2,p5,z)==0

# Canonical cyclic homogeneous module H=C[z]/(mA).
A=sp.Matrix([
    [0,0,0,0,0,384],
    [1,0,0,0,0,32],
    [0,1,0,0,0,-16],
    [0,0,1,0,0,8],
    [0,0,0,1,0,-4],
    [0,0,0,0,1,2],
])
e0=sp.Matrix([1,0,0,0,0,0])
assert sp.expand(A.charpoly(z).as_expr()-mA)==0

# Lambda4:
# D4 = C[z]/E^2, H4 = E^2 X4 ~= C[z]/mA.
# Lambda4([r]) = p3 r x4 = r(A) q(A) h0.
qA=sp.zeros(6)
for j in range(6):
    qA += sp.expand(q).coeff(z,j)*(A**j)
v4=qA*e0
B4=sp.Matrix.hstack(v4,A*v4)

assert B4 == sp.Matrix([
    [-192,384],
    [80,-160],
    [-32,64],
    [12,-24],
    [-4,8],
    [1,-2],
])
assert B4.rank()==1
assert (A+2*sp.eye(6))*B4 == sp.zeros(6,2)
assert B4*sp.Matrix([2,1]) == sp.zeros(6,1)

# Lambda5:
# D5=C[z]/p4 (dim 8), H5=p4 X5 ~= C[z]/mA (dim 6).
# In cyclic target basis y,Ay,...,A^5y, Lambda5(S^j)=A^j y.
B5=sp.Matrix.hstack(*[(A**j)*e0 for j in range(8)])
assert B5 == sp.Matrix([
    [1,0,0,0,0,0,384,768],
    [0,1,0,0,0,0,32,448],
    [0,0,1,0,0,0,-16,0],
    [0,0,0,1,0,0,8,0],
    [0,0,0,0,1,0,-4,0],
    [0,0,0,0,0,1,2,0],
])
assert B5.rank()==6

# Kernel has dimension 2 and is generated by mA and z*mA modulo p4.
mcoeff=[sp.expand(mA).coeff(z,j) for j in range(8)]
zmcoeff=[0]+[sp.expand(mA).coeff(z,j) for j in range(7)]
assert B5*sp.Matrix(mcoeff) == sp.zeros(6,1)
assert B5*sp.Matrix(zmcoeff) == sp.zeros(6,1)
assert sp.Matrix.hstack(sp.Matrix(mcoeff),sp.Matrix(zmcoeff)).rank()==2
assert len(B5.nullspace())==2

# Krylov/resultant polynomial is nonzero.
# For r=1, landing is e0 and its Krylov matrix is identity.
K0=sp.Matrix.hstack(*[(A**j)*e0 for j in range(6)])
assert K0.det()==1

# Structural identity: for any polynomial r, Delta_A(r(A)e0)=det r(A).
# Nonzeroness follows already from r=1.
# In a cyclic companion module det r(A)=Res(mA,r).
assert sp.resultant(mA,sp.Integer(1),z)==1

print("v0.37 complete landing operators: PASS")
print("D4 ~= C[S]/(S+2)^2, dim 2")
print("Lambda4 rank 1 and (A+2I)Lambda4=0 identically")
print("ker Lambda4 = (S+2)D4")
print("D5 ~= C[S]/p4, dim 8")
print("Lambda5 rank 6, hence surjective onto H5")
print("ker Lambda5 = m_A D5, dim 2")
print("Delta_A o Lambda5 = Res(m_A,r_d), a nonzero degree-6 polynomial")
print("certificate Delta_A(Lambda5(1))=1")
