import StokesV5

#print axioms StokesV5.planeCLM_apply
#print axioms StokesV5.linearJacobian_comp
#print axioms StokesV5.smoothChart_jacobian_ne_zero
#print axioms StokesV5.mapJacobian_contDiffAt
#print axioms StokesV5.smooth_eventually_differentiable
#print axioms StokesV5.mapJacobian_comp
#print axioms StokesV5.mapJacobian_square_comp
#print axioms StokesV5.exceptional_not_hasWhitneyNormalFormAt

/-! Every public named theorem is audited; verify_lean.py checks completeness. -/

#print axioms StokesV5.AB_delta_identities
#print axioms StokesV5.AR_hasDerivAt
#print axioms StokesV5.AR_pos_on_open_unit
#print axioms StokesV5.AR_t_bigO_sq
#print axioms StokesV5.AR_t_expansion
#print axioms StokesV5.BR_hasDerivAt
#print axioms StokesV5.BR_neg_on_physical
#print axioms StokesV5.BR_t_expansion
#print axioms StokesV5.B_at_cLo_ne_zero
#print axioms StokesV5.B_at_one_ne_zero
#print axioms StokesV5.B_mul_uFold
#print axioms StokesV5.auxiliaryChirality_hasDerivAt
#print axioms StokesV5.auxiliaryChirality_strictAntiOn
#print axioms StokesV5.auxiliaryD_pos
#print axioms StokesV5.auxiliaryImage_third
#print axioms StokesV5.auxiliaryImage_third_squared
#print axioms StokesV5.auxiliaryMaximum_outside_physical
#print axioms StokesV5.auxiliaryMaximum_spec
#print axioms StokesV5.auxiliaryRadiusSquared_identity
#print axioms StokesV5.auxiliaryThirdSquared_hasDerivAt
#print axioms StokesV5.auxiliaryThirdSquared_strictAnti_after
#print axioms StokesV5.auxiliaryThirdSquared_strictMono_before
#print axioms StokesV5.auxiliaryThird_boundary_max
#print axioms StokesV5.auxiliary_endpoint
#print axioms StokesV5.boundary_q_decimal_bounds
#print axioms StokesV5.certificatePB_eval
#print axioms StokesV5.certificateQ17_eval
#print axioms StokesV5.certificateR7_eval
#print axioms StokesV5.chiralityPolynomial_irreducible_mod13
#print axioms StokesV5.chiralityPolynomial_irreducible_rational
#print axioms StokesV5.chiralityPolynomial_monic
#print axioms StokesV5.componentZero_not_rational_branch
#print axioms StokesV5.component_zero_iff
#print axioms StokesV5.coordinate_x_bigO
#print axioms StokesV5.coordinate_y_bigO
#print axioms StokesV5.cos_qChart_bigO_sq
#print axioms StokesV5.cos_taylor_quartic
#print axioms StokesV5.cos_tendsto_one
#print axioms StokesV5.critical_branches_transverse_at_zero
#print axioms StokesV5.curveRadius_at_zero
#print axioms StokesV5.curveRadius_continuousAt_zero
#print axioms StokesV5.curveRadius_eq_radialRadius
#print axioms StokesV5.curveRadius_t_expansion
#print axioms StokesV5.delta_bigO_sq
#print axioms StokesV5.delta_half_angle
#print axioms StokesV5.discriminantE_deriv_neg
#print axioms StokesV5.discriminantE_hasDerivAt
#print axioms StokesV5.discriminantE_strictAntiOn_physical
#print axioms StokesV5.discriminant_coefficients_at_one
#print axioms StokesV5.discriminant_contact_cubic_error
#print axioms StokesV5.discriminant_endpoint_M_decimal_bounds
#print axioms StokesV5.discriminant_endpoint_N_decimal_bounds
#print axioms StokesV5.discriminant_hasDerivAt_one
#print axioms StokesV5.discriminant_quadratic_contact
#print axioms StokesV5.exceptionalInverseU_bigO
#print axioms StokesV5.exceptionalInverse_contDiffAt_zero
#print axioms StokesV5.exceptionalJetError_affine_x
#print axioms StokesV5.exceptionalJetSlope_bigO
#print axioms StokesV5.exceptionalSource_isSmoothChart
#print axioms StokesV5.exceptional_coordinate_identity
#print axioms StokesV5.exceptional_coordinate_jet
#print axioms StokesV5.exceptional_four_jet_rescaling
#print axioms StokesV5.exceptional_inverse_left
#print axioms StokesV5.exceptional_inverse_right
#print axioms StokesV5.exceptional_jacobian_expansion
#print axioms StokesV5.exceptional_kernel_transversality_fails
#print axioms StokesV5.exceptional_not_isPlaneWhitneyFoldCriterionAt
#print axioms StokesV5.exceptional_ordinary_four_jet
#print axioms StokesV5.exceptional_weighted_expansions
#print axioms StokesV5.exists_unique_auxiliary_chirality
#print axioms StokesV5.exists_unique_pBR_zero_in_isolating_interval
#print axioms StokesV5.exists_unique_skeleton_intersection
#print axioms StokesV5.factorizedJacobianAtU_hasDerivAt
#print axioms StokesV5.factorizedJacobianMap_hasFDerivAt_onFold
#print axioms StokesV5.fderiv_observationJacobian_kernelVector
#print axioms StokesV5.foldFactor_hasFDerivAt
#print axioms StokesV5.foldM_contDiffAt
#print axioms StokesV5.foldM_delta_expansion
#print axioms StokesV5.foldM_exact_contact
#print axioms StokesV5.foldM_exact_delta
#print axioms StokesV5.foldM_hasDerivAt_one
#print axioms StokesV5.foldM_qC_expression
#print axioms StokesV5.foldM_reduced
#print axioms StokesV5.foldNDerivative_pos
#print axioms StokesV5.foldN_contDiffAt
#print axioms StokesV5.foldN_delta_expansion
#print axioms StokesV5.foldN_exact_contact
#print axioms StokesV5.foldN_exact_delta
#print axioms StokesV5.foldN_hasDerivAt
#print axioms StokesV5.foldRemainder_contDiffAt_diagonal
#print axioms StokesV5.foldRemainder_diagonal
#print axioms StokesV5.foldRemainder_diagonal_neg
#print axioms StokesV5.full_physical_discriminant
#print axioms StokesV5.gauss_translation_invariant
#print axioms StokesV5.inverseQCube_continuousAt_zero
#print axioms StokesV5.inverseQCube_expansion
#print axioms StokesV5.inverse_curveRadius_t_expansion
#print axioms StokesV5.jacobianConstant_expansion
#print axioms StokesV5.jacobianPrefactor_differentiableAt
#print axioms StokesV5.jacobianRaw_reduce
#print axioms StokesV5.jacobianSlope_expansion
#print axioms StokesV5.jetScalingSource_isSmoothChart
#print axioms StokesV5.jetScalingTarget_isSmoothChart
#print axioms StokesV5.kernelJacobianDerivative_uFoldR
#print axioms StokesV5.kernelVector_ne_zero_of_cos_lt
#print axioms StokesV5.linearJacobian_observationDerivative
#print axioms StokesV5.mapJacobian_observationMap
#print axioms StokesV5.mapJacobian_observationMap_eventuallyEq
#print axioms StokesV5.mapJacobian_observationMap_hasFDerivAt_symmetry
#print axioms StokesV5.near_one_chart
#print axioms StokesV5.numerator_exact_quadratic
#print axioms StokesV5.observationDerivative_kernelVector
#print axioms StokesV5.observationDerivative_kernel_exact
#print axioms StokesV5.observationDerivative_nonzero_of_cos_lt
#print axioms StokesV5.observationDerivative_symmetry_apply
#print axioms StokesV5.observationDerivative_symmetry_kernel
#print axioms StokesV5.observationDerivative_symmetry_nonzero
#print axioms StokesV5.observationJacobian_factorization
#print axioms StokesV5.observationJacobian_hasFDerivAt_onFold
#print axioms StokesV5.observationJacobian_symmetry_hasDerivAt
#print axioms StokesV5.observationJacobian_zero_of_foldEquation
#print axioms StokesV5.observationM_contDiffAt
#print axioms StokesV5.observationM_hasFDerivAt
#print axioms StokesV5.observationM_phase_form
#print axioms StokesV5.observationM_reduced
#print axioms StokesV5.observationMap_critical_iff
#print axioms StokesV5.observationMap_differentiableAt
#print axioms StokesV5.observationMap_even
#print axioms StokesV5.observationMap_fderiv_eq
#print axioms StokesV5.observationMap_hasExplicitFDerivAt
#print axioms StokesV5.observationMap_hasFDerivAt
#print axioms StokesV5.observationMap_rational_branch
#print axioms StokesV5.observationMap_symmetry
#print axioms StokesV5.observationN_hasFDerivAt
#print axioms StokesV5.observationN_second_deriv_symmetry
#print axioms StokesV5.observationN_slice_hasDerivAt
#print axioms StokesV5.observationNumerator_hasFDerivAt
#print axioms StokesV5.observation_weighted_jets
#print axioms StokesV5.ordinary_coordinates_bigO
#print axioms StokesV5.ordinary_physical_rational_normalForm
#print axioms StokesV5.pBR_deriv
#print axioms StokesV5.pBR_deriv_pos_on_unit
#print axioms StokesV5.pBR_eq_neg_AR_sub_BR
#print axioms StokesV5.pBR_nonneg_iff_boundary_le
#print axioms StokesV5.pBR_strictMonoOn_unit
#print axioms StokesV5.pB_at_cHi_pos
#print axioms StokesV5.pB_at_cLo_neg
#print axioms StokesV5.pB_eq_nFold_sub_B
#print axioms StokesV5.pB_zero_at_boundary_iff
#print axioms StokesV5.phaseCoeff_contDiffAt_one
#print axioms StokesV5.phaseCoeff_t_expansion
#print axioms StokesV5.physicalBoundary_decimal_bounds
#print axioms StokesV5.physicalBoundary_mem_unit
#print axioms StokesV5.physicalBoundary_spec
#print axioms StokesV5.physicalBoundary_unique_on_unit
#print axioms StokesV5.physical_critical_locus_iff
#print axioms StokesV5.physical_critical_point_normalForm
#print axioms StokesV5.physical_foldEquation_iff
#print axioms StokesV5.pow_bigO_zero
#print axioms StokesV5.q17R_pos_on_three_fifths
#print axioms StokesV5.qC_contDiffAt
#print axioms StokesV5.qC_delta_expansion
#print axioms StokesV5.qC_exact_fourth
#print axioms StokesV5.qC_exact_quadratic
#print axioms StokesV5.qC_exact_second
#print axioms StokesV5.qChart_comp_hasFDerivAt
#print axioms StokesV5.qChart_ne_zero
#print axioms StokesV5.qChart_pos
#print axioms StokesV5.qChart_sq
#print axioms StokesV5.qChart_t_expansion
#print axioms StokesV5.r7R_neg_on_unit
#print axioms StokesV5.radialCurve_first_expansion
#print axioms StokesV5.radialCurve_hasDerivAt_zero
#print axioms StokesV5.radialCurve_second_expansion
#print axioms StokesV5.radialCurve_third
#print axioms StokesV5.radialCurve_third_boundary_max
#print axioms StokesV5.radialCurve_third_expansion
#print axioms StokesV5.radialImage_at_boundary
#print axioms StokesV5.radialImage_at_one
#print axioms StokesV5.radialImage_mirror
#print axioms StokesV5.radialImage_third
#print axioms StokesV5.radialImage_third_boundary_max
#print axioms StokesV5.radialImage_third_sq
#print axioms StokesV5.radialImage_third_strictAntiOn
#print axioms StokesV5.radialImage_unit
#print axioms StokesV5.radialNPoly_eval
#print axioms StokesV5.radialQPoly_eval
#print axioms StokesV5.radialRPoly_pos
#print axioms StokesV5.radialRPoly_sum_squares
#print axioms StokesV5.radialRadiusSquared_continuousAt_one
#print axioms StokesV5.radialRadiusSquared_delta_expansion
#print axioms StokesV5.radialRadiusSquared_eq
#print axioms StokesV5.radialRadiusSquared_exact_delta
#print axioms StokesV5.radialRadiusSquared_pos
#print axioms StokesV5.radialRadius_delta_expansion
#print axioms StokesV5.radialThirdSquared_at_boundary
#print axioms StokesV5.radialThirdSquared_at_one
#print axioms StokesV5.radialThirdSquared_hasDerivAt
#print axioms StokesV5.radialThirdSquared_nonneg
#print axioms StokesV5.radialThirdSquared_strictAntiOn
#print axioms StokesV5.radialThird_boundary_max
#print axioms StokesV5.radialThird_deriv_neg
#print axioms StokesV5.radialThird_no_interior_critical
#print axioms StokesV5.radialThird_strictAntiOn
#print axioms StokesV5.radial_derivative_certificate
#print axioms StokesV5.radial_endpoint_norm_identity
#print axioms StokesV5.radial_normalization_expansion
#print axioms StokesV5.radial_translation_changes_map
#print axioms StokesV5.rationalBranch_hasWhitneyNormalFormAt
#print axioms StokesV5.rationalBranch_isPlaneWhitneyFoldCriterionAt
#print axioms StokesV5.rationalBranch_kernel_and_nonzero
#print axioms StokesV5.rationalBranch_kernel_transverse
#print axioms StokesV5.rationalCriticalGraph_hasDerivAt_zero
#print axioms StokesV5.rational_discriminant_at_boundary
#print axioms StokesV5.reduced_exact_fold_factor
#print axioms StokesV5.reduced_linear_critical
#print axioms StokesV5.rowCLM_apply
#print axioms StokesV5.sin_bigO_id
#print axioms StokesV5.sin_taylor_cubic
#print axioms StokesV5.skeletonEPoly_eval
#print axioms StokesV5.skeleton_fold_intersection_iff
#print axioms StokesV5.smoothChart_of_rows
#print axioms StokesV5.spherical_endpoint_decimal_bounds
#print axioms StokesV5.sturm_variations_pB
#print axioms StokesV5.sturm_variations_q17
#print axioms StokesV5.sturm_variations_r7
#print axioms StokesV5.surfaceFold_at_zero
#print axioms StokesV5.surfaceFold_first_expansion
#print axioms StokesV5.surfaceFold_hasDerivAt_zero
#print axioms StokesV5.surfaceFold_is_ruledSurface
#print axioms StokesV5.surfaceFold_second_expansion
#print axioms StokesV5.surfaceFold_third_expansion
#print axioms StokesV5.symmetryCriticalGraph_hasDerivAt_zero
#print axioms StokesV5.symmetry_discriminant_image
#print axioms StokesV5.symmetry_hasWhitneyNormalFormAt
#print axioms StokesV5.symmetry_isPlaneWhitneyFoldCriterionAt
#print axioms StokesV5.symmetry_kernel_transverse
#print axioms StokesV5.symmetry_normalForm_identity
#print axioms StokesV5.symmetry_second_order_fold_determinant
#print axioms StokesV5.uFoldR_at_boundary
#print axioms StokesV5.uFoldR_at_one
#print axioms StokesV5.uFoldR_foldEquation
#print axioms StokesV5.uFoldR_mem_unit_iff
#print axioms StokesV5.uFold_delta_expansion
#print axioms StokesV5.uFold_exact_delta
#print axioms StokesV5.uFold_is_jacobian_root
#print axioms StokesV5.uFold_t_bigO_sq
#print axioms StokesV5.uFold_t_expansion
#print axioms StokesV5.weighted_fst_bigO
#print axioms StokesV5.weighted_snd_bigO
